// Generated by gencpp from file gazebo_sfm_plugin/ped_state.msg
// DO NOT EDIT!


#ifndef GAZEBO_SFM_PLUGIN_MESSAGE_PED_STATE_H
#define GAZEBO_SFM_PLUGIN_MESSAGE_PED_STATE_H

#include <ros/service_traits.h>


#include <gazebo_sfm_plugin/ped_stateRequest.h>
#include <gazebo_sfm_plugin/ped_stateResponse.h>


namespace gazebo_sfm_plugin
{

struct ped_state
{

typedef ped_stateRequest Request;
typedef ped_stateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ped_state
} // namespace gazebo_sfm_plugin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_sfm_plugin::ped_state > {
  static const char* value()
  {
    return "05beeb87454630bfc7ea88a89fd9b876";
  }

  static const char* value(const ::gazebo_sfm_plugin::ped_state&) { return value(); }
};

template<>
struct DataType< ::gazebo_sfm_plugin::ped_state > {
  static const char* value()
  {
    return "gazebo_sfm_plugin/ped_state";
  }

  static const char* value(const ::gazebo_sfm_plugin::ped_state&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_sfm_plugin::ped_stateRequest> should match
// service_traits::MD5Sum< ::gazebo_sfm_plugin::ped_state >
template<>
struct MD5Sum< ::gazebo_sfm_plugin::ped_stateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_sfm_plugin::ped_state >::value();
  }
  static const char* value(const ::gazebo_sfm_plugin::ped_stateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_sfm_plugin::ped_stateRequest> should match
// service_traits::DataType< ::gazebo_sfm_plugin::ped_state >
template<>
struct DataType< ::gazebo_sfm_plugin::ped_stateRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_sfm_plugin::ped_state >::value();
  }
  static const char* value(const ::gazebo_sfm_plugin::ped_stateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_sfm_plugin::ped_stateResponse> should match
// service_traits::MD5Sum< ::gazebo_sfm_plugin::ped_state >
template<>
struct MD5Sum< ::gazebo_sfm_plugin::ped_stateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_sfm_plugin::ped_state >::value();
  }
  static const char* value(const ::gazebo_sfm_plugin::ped_stateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_sfm_plugin::ped_stateResponse> should match
// service_traits::DataType< ::gazebo_sfm_plugin::ped_state >
template<>
struct DataType< ::gazebo_sfm_plugin::ped_stateResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_sfm_plugin::ped_state >::value();
  }
  static const char* value(const ::gazebo_sfm_plugin::ped_stateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_SFM_PLUGIN_MESSAGE_PED_STATE_H
